routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('lists.index');
});
Route::resource('lists', \App\Http\Controllers\Web\ListController::class);
Route::resource('records', \App\Http\Controllers\Web\RecordController::class);
Route::post('records/store/api', [\App\Http\Controllers\Web\RecordController::class, 'storeApi']);

app/Http/Controllers/Api/ListController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Repositories\ColumnRepository;
use App\Repositories\UserListRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ListController extends Controller
{
    private $lists;
    private $columns;
    public function __construct(UserListRepository $listRepository, ColumnRepository $columnRepository)
    {
        $this->lists = $listRepository;
        $this->columns = $columnRepository;
    }

    public function lists(Request $request)
    {
        $lists = $this->lists->getAll();
        return Response::json($lists);
    }

    public function records($listID, Request $request)
    {
        $list = $this->lists->find($listID, ['columns']);
        $page = request('page', 1);
        $perPage = $list->per_page;
        $offset = ($page - 1) * $perPage;
        $activeColumns = $list->columns->where('status', '=', '1')->pluck('_id')->toArray();
        $perPage = $perPage * count($activeColumns); // each record contains multiple columns so per page should be per_page * columns count;

        $recordsGroupID = $list->records();

        // search in records by specific columns
        $searched = null;
        if ($request->has('search_by') && strlen(trim($request->search_value)) > 0) {
            $column = $list
                ->columns
                ->where('_id', $request->search_by)
                ->first();
            if ($column != null) {
                $searched = [
                    'column' => $column->id,
                    'search' => $request->search_value ?? ''
                ];
                $columnID = $column->id;
                $recordsGroupID = $recordsGroupID
                    ->where('column_id', $columnID)
                    ->where('content', 'LIKE', "%" . $request->search_value . "%");
            }
        }

        $totalRecords = $recordsGroupID->count();

        // search result records grouped by "group_id"
        $recordsGroupID = $recordsGroupID
            ->skip($offset)
            ->take($perPage)
            ->pluck('group_id')
            ->toArray();

        $recordsGroupID = array_unique($recordsGroupID);

        // get records
        $searchedRecords = $list
            ->records()
            ->whereIn('group_id', $recordsGroupID)
            ->whereIn('column_id', $activeColumns)
            ->get()
            ->groupBy('group_id')
            ->toArray();

        // sort records based on specific column
        $records = [];
        $sortBy = null;
        if ($request->has('sort_by')) {
            $column = $list->columns->where('_id', $request->sort_by)->first();
            if ($column != null) {
                $primaryRecords = null;
                $sortBy = $column->id;
                foreach ($searchedRecords as $index => $item) {
                    $column = array_filter($item, function($ar) use ($sortBy) {
                        return ($ar['column_id'] == $sortBy);
                    });
                    $column = array_values($column);
                    $primaryRecords[$index] = $column[0]['content'];
                }
                if ($primaryRecords != null) {
                    asort($primaryRecords);
                    foreach ($primaryRecords as $index => $record) {
                        $records[$index] = $searchedRecords[$index];
                    }
                }
            }
        }

        return Response::json([
            'data' => count($records) > 0 ? $records : $searchedRecords,
            'sort_by' => $sortBy,
            'searched' => $searched,
            'meta' => [
                'current_page' => $page,
                'per_page' => $perPage,
                'total_pages' => ceil($totalRecords / $perPage),
                'total_records' => $totalRecords / count($activeColumns)
            ]
        ], 200);
    }
}

app/Http/Controllers/Web/ListController.php
<?php

namespace App\Http\Controllers\Web;

use App\Helpers\Paginator;
use App\Http\Controllers\Controller;
use App\Http\Requests\Web\ListRequest;
use App\Repositories\ColumnRepository;
use App\Repositories\UserListRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ListController extends Controller
{
    private $list;
    private $column;
    public function __construct(UserListRepository $listRepository, ColumnRepository $columnRepository)
    {
        $this->list = $listRepository;
        $this->column = $columnRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $lists = $this->list->getAll();
        return view('lists.index', compact('lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('lists.create');
    }

    /**
     * Creating new User List with its columns
     *
     * @param ListRequest $request
     * @return JsonResponse
     */
    public function store(ListRequest $request)
    {
        $list = $this->list->store($request->only(['meta_data', 'title', 'per_page']));
        foreach ($request->columns as $column) {
            $column['list_id'] = $list->id;
            $column = $this->column->store($column);
        }
        return Response::json([
            'message' => 'Your list created successfully.',
            'data' => $list->with('columns')
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function show($id)
    {
        $list = $this->list->find($id, ['columns', 'records' ]);
        $columns = $list->columns->where('status', '1');
        $records = $list->records
            ->whereIn('column_id', $columns->pluck('_id')->toArray())
            ->groupBy('group_id');
        $records = Paginator::paginate($records, $list->per_page)->setPath('/lists/' . $list->id);

        $data = [
            'records' => $records,
            'columns' => $columns,
            'list' => $list
        ];
        return view('lists.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $list = $this->list->find($id, ['columns']);
        return view('lists.edit', compact('list'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return JsonResponse
     */
    public function update($id, ListRequest $request)
    {
        $list = $this->list->update($id, $request->only(['meta_data', 'title', 'per_page']));
        foreach ($request->columns as $column) {
            $column = $this->column->update($column['id'], collect($column)->except('id')->toArray());
        }
        return Response::json([
            'message' => 'Your list updated successfully.',
            'data' => $list->with('columns')
        ]);
    }

    /**
     * Remove the specified List with all of its columns and records.
     *
     * @param  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $this->list->destroy($id);
        return redirect()->back()->with('success_message', 'Your list deleted successfully.');
    }
}

resources/views/lists/index.blade.php
@extends('layouts.app')

@section('title', $title = 'lists')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{ $title }}
                        <a href="{{ route('lists.create') }}" class="btn btn-outline-primary float-right">
                            <i class="fa fa-plus"></i> create list
                        </a>
                    </h4>

                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>title</th>
                            <th>columns</th>
                            <th>action</th>
                        </tr>
                        </thead>
                        <tbody>
{{--                        @foreach($lists as $list)--}}
                            {{--<tr>
                                <td width="60%"><strong>{{ $list->title }}</strong></td>
                                <td width="30%">
                                    @foreach($list->columns as $column)
                                        <div >
                                            <p><strong class="btn btn-sm mb-1 btn-disabled btn-success">{{ $column->title }}</strong></p>
                                        </div>
                                    @endforeach
                                </td>
                                <td>
                                    <a href="{{ route('lists.show', ['list' => $list->id]) }}" class="btn btn-primary mb-1 btn-sm">Show</a>
                                    <button onclick="confirmDestroy('destroy-{{ $list->id }}')" class="btn btn-danger mb-1 btn-sm">Delete</button>
                                    <form method="POST" action="{{ route('lists.destroy', ['list' => $list->id]) }}" style="display: none;" id="destroy-{{ $list->id }}"> @method('DELETE') @csrf </form>
                                    <a href="{{ route('lists.edit', ['list' => $list->id]) }}" class="btn btn-info btn-sm">Update</a>
                                </td>
                            </tr>--}}
{{--                        @endforeach--}}
                        </tbody>
                    </table>
                    <hr>
                    <nav id="pagination" aria-label="Page navigation example">
                        <ul class="pagination" id="pages">
                            <li class="page-item page-num"><a class="page-link" href="#">1</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        // destroy list
        function confirmDestroy(id) {
            Swal.fire({
                icon: 'warning',
                title: "Are sure about delete list?!",
                showDenyButton: true,
                showCancelButton: false,
                confirmButtonText: 'Delete',
                denyButtonText: `Don't delete`,
            }).then((result) => {
                if (result.isConfirmed) {
                    $(`#${id}`).submit();
                }
            })
        }

        // render lists table
        function renderTable (page = 1, per_page = 15) {
            $.get({
                url: `/api/lists?per_page=${per_page}&page=${page}`,
                success: function (response) {
                    // render list table records
                    $('tbody').empty();
                    $.each(response.data, function () {
                        let columns = '';
                        $.each(this.columns, function () {
                            columns +=
                                `<div >
                                    <p><strong class="btn btn-sm mb-1 btn-disabled btn-success">${this.title}</strong></p>
                                </div>`
                        })
                        let csrf = $('meta[name=csrf]').attr('content')
                        let tr =
                            `<tr>
                                <td width="60%"><strong>${this.title}</strong></td>
                                <td width="30%">
                                    ${columns}
                                </td>
                                <td>
                                    <a href="/lists/${this._id}" class="btn btn-primary mb-1 btn-sm">Show</a>
                                    <button onclick="confirmDestroy('destroy-${this._id}')" class="btn btn-danger mb-1 btn-sm">Delete</button>
                                    <form method="POST" action="/lists/${this._id}" style="display: none;" id="destroy-${this._id}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="${csrf}">
                                    </form>
                                    <a href="/lists/${this._id}/edit" class="btn btn-info btn-sm">Update</a>
                                </td>
                            </tr>`
                        $(tr).appendTo('tbody');
                    });

                    // render list table pagination
                    $(document).find('.page-num').remove();
                    for (let page = 1; page <= response.meta.total_pages; page++) {
                        let is_active = '';
                        if (page == response.meta.current_page) {
                            is_active = 'active'
                        } else {
                            is_active = ''
                        }
                        let page_item =
                            `<li class="page-item page-num ${is_active}" data-page="${page}"><a class="page-link" href="#!">${page}</a></li>`
                        $('#pages').append(page_item);
                    }
                }
            });
        }
        $(document).ready(function () {
            renderTable(1, 15);
            $(document).on('click', '.page-num', function () {
                renderTable($(this).data('page'), 15);
            })
        });
    </script>
@endsection

resources/views/lists/show.blade.php
@extends('layouts.app')

@section('title', $data['list']->title ?? 'list showing')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card mb-5">
                <div class="card-header">
                    <h4 class="card-title" id="list" data-listID="{{ $data['list']->id }}">
                        {{ $data['list']->title ?? 'list showing' }}
                        <a href="{{ route('lists.index') }}" class="btn btn-outline-primary float-right"> back </a>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="row pb-3">
                        <h4>Insert new record</h4>
                        @foreach($data['columns'] as $column)
                        <div class="col-lg-6 col-sm-12 pr-3 pl-3 pb-2">
                            <div class="form-group">
                                <label>{{ $column->title }}</label>
                                @switch($column->data_type)
                                    @case('string') <input type="text" data-column="{{ $column->id }}" class="form-control record-value"> @break
                                    @case('integer') <input type="number" data-column="{{ $column->id }}" class="form-control record-value"> @break
                                    @case('dateTime') <input type="date" data-column="{{ $column->id }}" class="form-control record-value"> @break
                                    @case('float') <input type="number" data-column="{{ $column->id }}" class="form-control record-value"> @break
                                    @case('enum')
                                        <select class="form-control record-value" data-column="{{ $column->id }}">
                                            @foreach(explode(',', $column->allowed) as $option)
                                                <option value="{{ $option }}">{{ $option }}</option>
                                            @endforeach
                                        </select>
                                        @break
                                @endswitch
                            </div>
                        </div>
                        @endforeach
                        <div class="col-12 d-grid">
                            <button id="insert-record" class="btn btn-success"> <i class="fa fa-check"></i> save </button>
                        </div>
                    </div>
                    <hr>
                    <form action="{{ url('records/store/api') }}" method="POST">
                        <div class="row pb-3">
                            <h4>Insert records from external resource</h4>
                            <div class="col-12 pr-3 pl-3 pb-2">
                                <div class="form-group">
                                    <label>Api</label>
                                    <input type="url" name="api" class="form-control">
                                    @csrf
                                    <input type="hidden" name="list_id" value="{{ $data['list']->id }}">
                                </div>
                            </div>
                            <div class="col-12 d-grid">
                                <button  class="btn btn-info"> <i class="fa fa-upload"></i> start </button>
                            </div>
                        </div>
                    </form>
                    <hr>
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            @foreach($data['columns'] as $column)
                                <th width="{{ $column->width_percent  }}%">
                                    {{ $column->title }}
                                    @if($column->sortable)
                                        <button data-column="{{ $column->id }}" data-list="{{ $data['list']->id }}" class=" btn btn-sm btn-icon btn-outline-primary sort-column"><i class="fa fa-sort"></i></button>
                                    @endif
                                    @if($column->searchable)
                                        <input data-column="{{ $column->id }}" ata-list="{{ $data['list']->id }}" type="text" class="form-control search-column" placeholder="search">
                                    @endif
                                </th>
                            @endforeach
                        </tr>
                        </thead>
                        <tbody>
                        @if($data['records']->count() > 0)
                            @foreach($data['records'] as $groupID => $items)
                                <tr data-group="{{ $groupID }}">
                                    @foreach($items as $item)
                                        <td>{{ $item->content }}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td class="text-center" colspan="{{ $data['columns']->count() }}">
                                    No data available
                                </td>
                            </tr>
                        @endif
                        </tbody>
                    </table>

                    {!! $data['records']->links() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        const list_id = "{{ $data['list']->id }}";
        function getRecords() {
            let sort = localStorage.getItem('sort')
            let page = localStorage.getItem('page')
            let searched = localStorage.getItem('searched')
            $.get({
                url: `/api/lists/${list_id}/records?${sort}&${searched}&${page}`,
                success: function (response) {
                    $('tbody').empty();
                    $.each(response.data, function (key, value) {
                        let tds = '';
                        $.each(value, function () {
                            tds += `<td>${this.content}</td>`
                        });
                        let record =
                            `<tr data-group="${key}">${tds}</tr>`
                        $('tbody').append(record)
                    });

                    $('nav>ul').empty();
                    for (let page = 1; page <= response.meta.total_pages; page++) {
                        let is_active = '';
                        if (page == response.meta.current_page) {
                            is_active = 'active'
                        } else {
                            is_active = ''
                        }
                        let page_item =
                            `<li class="page-item page-num ${is_active}" data-page="${page}"><a class="page-link" href="#!">${page}</a></li>`
                        $('nav>ul').append(page_item);
                    }
                }
            });
        }

        $('#insert-record').click(function () {
            let record = [];
            $('.record-value').each(function () {
                let column_id = $(this).data('column');
                let column_value = $(this).val();
                record.push({
                    'column_id': column_id,
                    'column_value': column_value
                });
            });
            $.post({
                url: "{{ route('records.store') }}",
                data: {
                    _token: "{{ @csrf_token() }}",
                    list_id: "{{ $data['list']->id }}",
                    record: record
                },
                success: function (response) {
                    Swal.fire({
                        icon: 'success',
                        title: response.message,
                        showConfirmButton: false,
                        timer: 2500
                    }).then(function () {
                        $('input').val('')
                        $('select').val('')
                    });
                },
                error: function (error) {
                    Swal.fire({
                        icon: 'error',
                        title: error.responseJSON.message,
                        showConfirmButton: false,
                        timer: 2500
                    })
                }
            });
        });

        $(document).on('click', '.sort-column', function () {
            let column_id = $(this).data('column');
            localStorage.setItem('sort', `sort_by=${column_id}`)
            getRecords();
        });

        $(document).on('click', '.page-num', function () {
            let page = $(this).data('page')
            localStorage.setItem('page', `page=${page}`)
            getRecords();
        });

        $(document).on('keyup', '.search-column', function () {
            let value = $(this).val();
            let column_id = $(this).data('column');
            $(document).find('.search-column').each(function () {
                $(this).val('');
            });
            $(this).val(value);
            localStorage.setItem('searched', `search_by=${column_id}&search_value=${value}`)
            getRecords();
        })
    </script>
@endsection